index:
    path: /
    controller: App\Controller\DefaultController::index

currency_conversion:
    path: /convert/{currencySource}/{currencyTarget}/{amount}
    controller: App\Controller\CurrencyConverterController::convert
    requirements:
        currencySource: '[A-Z]{3}'
        currencyTarget: '[A-Z]{3}'
        amount: '[0-9\.]+'
